CREATE DATABASE IF NOT EXISTS ALMACEN;
USE ALMACEN;

CREATE TABLE CATEOGORIA (
IDCATEGORIA INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(255) NOT NULL
);
CREATE TABLE MARCA (
IDMARCA INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(255) NOT NULL
);
CREATE TABLE PRECIO (
IDPRECIO INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(255) NOT NULL
);
CREATE TABLE STOCK (
IDSTOCK INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(255) NOT NULL
);
CREATE TABLE PRODUCTOS (

IDPRODUCTOS INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(255) NOT NULL,
  IDCATEGORIA INT,
  IDMARCA INT,
  IDPRECIO INT,
  IDSTOCK INT,
  FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
  FOREIGN KEY (IDMARCA) REFERENCES MARCA(IDMARCA),
  FOREIGN KEY (IDPRECIO) REFERENCES PRECIO(IDPRECIO),
  FOREIGN KEY (IDSTOCK) REFERENCES STOCK(IDSTOCK)
);